name: Issue Comment Workflow
on:
 issues:
   types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
       - name:  "dump github context"
         run: echo '${{ (github.event) }}' | jq
         shell: bash
   
   
